#!/bin/sh

# This script creates an IBC transaction from the "bank" account on the gaiad chain and funds the
# destination account on the microtick chain with the requested amount of tokens

CHAINID_GAIAD=$(jq -r .chain_id ./config/gaiad.json)

usage() {
  echo "fund [account] [amount]"
  exit 1
}

if [ -z "$1" ]; then
  usage
fi
ACCOUNT=$1

if [ -z "$2" ]; then
  usage
fi
AMOUNT=$2

SILENT=1
redirect() {
  if [ "$SILENT" -eq 1 ]; then
    "$@" > /dev/null 2>&1
  else
    "$@"
  fi
}

echo "Sending tokens over IBC..."
redirect gaiad tx ibc-transfer transfer transfer channel-0 $ACCOUNT $AMOUNT --from bank --home ./data/gaiad --keyring-backend test --node tcp://localhost:26557 --chain-id $CHAINID_GAIAD -y 
