#!/bin/sh

CHAINID_GAIAD=$(jq -r .chain_id ./config/gaiad.json)

usage() {
  echo "send [account] [amount]"
  exit 1
}

if [ -z "$1" ]; then
  usage
fi
ACCOUNT=$1

if [ -z "$2" ]; then
  usage
fi
AMOUNT=$2

SILENT=1
redirect() {
  if [ "$SILENT" -eq 1 ]; then
    "$@" > /dev/null 2>&1
  else
    "$@"
  fi
}

echo "Transferring tokens to gaiad account"

BANK=$(gaiad keys show bank -a --home ./data/gaiad --keyring-backend test)
redirect gaiad tx bank send $BANK $ACCOUNT $AMOUNT --home ./data/gaiad --keyring-backend test --node tcp://localhost:26557 --chain-id $CHAINID_GAIAD -y

