#!/bin/bash

DATA=$PWD/data

SILENT=0
redirect() {
  if [ "$SILENT" -eq 1 ]; then
    "$@" > /dev/null 2>&1
  else
    "$@"
  fi
}

pkill gaiad
pkill mtm

redirect gaiad start --home $DATA/gaiad &
redirect mtm start --home $DATA/microtick &

